### ISSUE TITLE
MAC error

### ISSUE THREAD

**Issue by heyeboine** [lasa01/io_import_vmf#159] opened 2023-03-30 16:19 UTC
Python: Traceback (most recent call last):
  File "/Users/xinxin/Library/Application Support/Blender/3.3/scripts/addons/io_import_vmf/__init__.py", line 1091, in execute
    from . import import_vmt
  File "/Users/xinxin/Library/Application Support/Blender/3.3/scripts/addons/io_import_vmf/import_vmt.py", line 10, in <module>
    from . import import_vtf
  File "/Users/xinxin/Library/Application Support/Blender/3.3/scripts/addons/io_import_vmf/import_vtf.py", line 4, in <module>
    from pyvtflib import VTFLib, VTFImageFlag, VTFImageFormat
  File "/Users/xinxin/Library/Application Support/Blender/3.3/scripts/addons/io_import_vmf/deps/pyvtflib/__init__.py", line 384, in <module>
    _vtflib = CDLL(_library_path)
  File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/xinxin/Library/Application Support/Blender/3.3/scripts/addons/io_import_vmf/deps/pyvtflib/bin/libVTFLib13.so, 0x0006): tried: '/Users/xinxin/Library/Application Support/Blender/3.3/scripts/addons/io_import_vmf/deps/pyvtflib/bin/libVTFLib13.so' (not a mach-o file)

**Comment by lasa01** [comment] 2023-04-08 10:52
Closing as a duplicate of your other issue.

**Closed** 2023-04-08 10:52 UTC
