### ISSUE TITLE
No instances

### ISSUE THREAD

**Issue by DrPeeper228** [lasa01/io_import_vmf#150] opened 2023-01-14 06:00 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when instances are missing

**Is your feature request related to a specific game? Please specify.**
Portal 2
**Describe the solution you'd like**
import the instance map to needed position

**Additional context**
nop

**Comment by lasa01** [comment] 2023-01-14 18:16
Duplicate of #132.

**Closed by lasa01** 2023-01-14 18:16 UTC
Labels: enhancement
