### ISSUE TITLE
No env_projectedtexture

### ISSUE THREAD

**Issue by DrPeeper228** [lasa01/io_import_vmf#152] opened 2023-01-14 07:10 UTC
**Describe the bug**
they aren't importing(env_projectedtextures are lights)

**To Reproduce**
1. Import any map with it
2. See error

**Expected behavior**
They are suppose to appear

**Related files**
you can use any maps from puzzlemaker, bc big observation room contains it

**Logs**
```
Read prefs: C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Info: Deleted 1 object(s)

Info: Deleted 1 object(s)

Writing userprefs: 'C:\Users\Velton\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend' ok
Info: Preferences saved

Indexing game files...
Indexing done in 5.106785535812378 s
Started importing VMF 'C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\flings_collapsed.vmf'
[1/12] Parsing map...
[2/12] Determining required game files...
[WARNING] UNSUPPORTED MATERIAL PARAMS: $forceexpensive, $flowmap, $flow_normaluvscale, $flow_worlduvscale, $flow_timeintervalinseconds, $flow_uvscrolldistance, $flow_bumpstrength, $flow_noise_texture, $flow_noise_scale, $flow_debug, $color_flow_uvscale, $color_flow_timeintervalinseconds, $color_flow_uvscrolldistance, $color_flow_lerpexp, $color_flow_displacebynormalstrength, $forceenvmap, $reflecttint, $abovewater, $bottommaterial, $fogstart, $fogend, $lightmapwaterfog, $flashlighttint in nature/toxicslime_a3_crazy_box
[WARNING] UNSUPPORTED MATERIAL PARAMS: $seamless_scale in nature/blendrockdirt_tunnel03a
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation in elevator/elevator_screen
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_wall_metal_002d
[WARNING] UNSUPPORTED MATERIAL PARAMS: $nofog in tools/toolsblack_noportal_nofog
[WARNING] UNSUPPORTED MATERIAL PARAMS: $normalmapenvmapmask in wood/underground_plywood_01a
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation, $envmaplightscale in metal/underground_black_tile001a
[WARNING] UNSUPPORTED MATERIAL PARAMS: $ssbumpmathfix, $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_wall_metal_002c
[WARNING] UNSUPPORTED MATERIAL PARAMS: $ssbumpmathfix, $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_wall_metal_002a
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_wall_metal_004c
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_floor_metal_001c
[WARNING] UNSUPPORTED MATERIAL PARAMS: %nopaint in metal/backstage_grate_001a
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation, $envmaplightscale in metal/underground_wall_metal004b_top
[WARNING] UNSUPPORTED MATERIAL PARAMS: %nopaint in metal/underground_metalgrate001a_alphatest
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmapcontrast, $envmapsaturation, $envmaplightscale in metal/underground_wall_metal004b
[WARNING] UNSUPPORTED MATERIAL PARAMS: $envmaplightscale, $envmapcontrast, $envmapsaturation in metal/black_wall_metal_004a
[3/12] Importing 26 models (reusing 0 existing)...
[3/12] Importing models... 19.2308 %
[3/12] Importing models... 38.4615 %
[ERROR]: MODEL models/props_ingame/arm_4panel LOADING FAILED: models/props_ingame
[3/12] Importing models... 57.6923 %
[3/12] Importing models... 76.9231 %
[3/12] Importing models... 96.1538 %
[3/12] Importing models... 100.0000 %
[4/12] Importing 60 textures (reusing 0 existing) and 46 materials (reusing 0 existing, 0 cannot be imported)...
[4/12] Importing textures... 16.6667 %
[4/12] Importing textures... 33.3333 %
[4/12] Importing textures... 50.0000 %
[4/12] Importing textures... 66.6667 %
[4/12] Importing textures... 83.3333 %
[4/12] Importing textures... 100.0000 %
[5/12] Importing materials... 100.0000 %
[6/12] Building geometry...
[6/12] Building geometry... 36.2319 %
[6/12] Building geometry... 72.4638 %
[WARNING] UNSUPPORTED MATERIAL PARAMS: $flowmap, $flowbounds, $flow_noise_texture, $flow_uvscrolldistance, $flow_timeintervalinseconds, $flow_noise_scale, $flow_lerpexp, $flow_worlduvscale, $flow_normaluvscale, $additive, $flow_color, $flow_vortex_color, $flow_vortex_size, $intensitynoise, $totalintensity in effects/fizzler_underground_side_emitters
[ERROR] LOADING SOLID FAILED: material effects/fizzler_underground_side_emitters hasn't been loaded
[6/12] Building geometry... 100.0000 %
[7/12] Building overlays...
[7/12] Building overlays... 100.0000 %
[8/12] Placing props...
[ERROR] LOADING PROP FAILED: model models/props_ingame/arm_4panel hasn't been imported
[8/12] Placing props... 69.9301 %
[8/12] Placing props... 100.0000 %
[9/12] Optimizing props...
[10/12] Placing lights...
[10/12] Placing lights... 100.0000 %
[11/12] Importing skybox...
[12/12] Skipped sky origin
Done in 163.2143 s
Imported 275 solids (1 failed)
Imported 6 overlays (0 failed)
Imported 142 props (1 failed)
Imported 54 lights (0 failed)
Info: Deleted 1 object(s)

Info: Total files 0 | Changed 0 | Failed 0
Info: Deleted 1 object(s)
```
You can open the console with `Window -> Toggle System Console` on Windows.

**Screenshots**
https://i.imgur.com/kf6PEf0.png
This map is mostly lit with env_projectedtexture

**Details (please complete the following information):**
 - OS: Windows 10
 - Blender Version: newest
 - Addon Version: newest
 - Did you download a release or build the addon yourself: downloaded a release
 - Related Game: Portal 2

**Additional context**

**Comment by lasa01** [comment] 2023-01-14 18:20
Duplicate of #141.

**Closed by lasa01** 2023-01-14 18:20 UTC
Labels: bug
